/*
 * InveSTICKgator Copyright (C) 2016 Frogtoss Games, Inc
 * 
 */

// This file contains build-specific values.
// 
// The values are stubbed to null defaults for local compiles
// and have little meaning on their own.
// 
// This file should be regenerated by a build server.

#pragma once

// name of the machine that compiled the build.
#define BUILDERNAME "(local build)"

// unique build event number from builder.  
const unsigned int BUILDNUMBER=0;

// Git short hash or similar
#define REVISION "0000000"

// Git long hash (or same as REVISION)
#define REVISION_LONG "0000000000000000000000000000000000000000"

// Build timestamp string
#define BUILD_TIMESTAMP "Tue 01/01/1900  00:00:00.00"

